#---------------- RL config ------------------
# only for DDPG and TD3
GAME : "flateplate"

HIDDEN_LAYERS : [32, 32, 32]    # NN size

MEMORY_CAPACITY : 500000        # for the Replay Memory
BATCH_SIZE : 64
GAMMA : 0.99                    # discount factor
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001
TAU : 0.005                     # update parameter of the target network

EXPLO_SIGMA : 0.05              # exploration noise
ACTION_SIGMA : 0                # additional noise (between chosen and actual action)

MAX_EPISODES : 10               # number of training episodes
MAX_STEPS : 350                 # max steps per episode

# saving and plotting parameters
FREQ_PLOT : 5
FREQ_EVAL : 25
FREQ_SAVE : 250

# next 2 parameters only used if agent=TD3 set according to the founding paper
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5


#---------------- CFD config -----------------
DELTA_TIME : 0.0001             # time step
POINTB_CHANGE : 200000          # change B every POINTB_CHANGE episodes

# initial position
XA : 0.06
YA : 0.035
UA : -1
VA : 0.1

# target position, B must be at most 10 deg from the horizontal axis with respect to A
XB : 0.03
YB : 0.04
