# config file for DDPG
GAME : "flateplate"
# GAME : "BipedalWalker-v2"
# GAME : "RoboschoolHalfCheetah-v0"
# GAME : "MountainCarContinuous-v0"

HIDDEN_LAYERS : [8, 8]  # Size of the NN
# HIDDEN_LAYERS : [8, 8, 8]

MEMORY_CAPACITY : 500000
BATCH_SIZE : 64
GAMMA : 0.99
LEARNING_RATE_CRITIC : 0.001
LEARNING_RATE_ACTOR : 0.001
TAU : 0.005

EXPLO_SIGMA : 0.05  # Exploration noise
# next 2 only used if agent TD3
UPDATE_SIGMA : 0.2
UPDATE_CLIP : 0.5

MAX_EPISODES : 1000
MAX_STEPS : 350  # Max steps per episode

FREQ_PLOT : 5
FREQ_EVAL : 25
FREQ_SAVE : 250


#---------------------------------------------
# Solver details (for the set of differential equations)
DELTA_TIME : 0.0001             #time step
# initial and final conditions to reach
XA : 0.06
YA : 0.035
UA : -1  # 3.1333
VA : 0.1
# set as final conditions a point located with at most 10degrees from the horizontal
# axis with respect to the initial point
XB : 0.03
YB : 0.04
POINTB_CHANGE : 200000           # number of episodes keeping same final point if
                               # desired to change the final point of the path
ACTION_SIGMA : 0
